# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color:rgb(56,56,86);\n"
"    color:rgb(220,220,220);\n"
"    border-radius:10px\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(10, 79, 641, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 80, 141)")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_disc = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_disc.setGeometry(QtCore.QRect(0, 150, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_disc.setFont(font)
        self.label_disc.setStyleSheet("color:rgb(2, 127, 127)")
        self.label_disc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disc.setObjectName("label_disc")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(80, 272, 521, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(96, 114, 165);\n"
"    color: rgb(255, 80, 141);\n"
"    border-style:none;\n"
"    border-radius:10px;\n"
"    text-align:center;\n"
"    color:#fff;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.517, stop:0 rgba(254, 138, 204, 255), stop:1 rgba(183, 105, 255, 255));\n"
"    \n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(20, 300, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color:rgb(2, 127, 127)")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_created = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_created.setGeometry(QtCore.QRect(50, 340, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_created.setFont(font)
        self.label_created.setStyleSheet("color: rgb(96, 114, 165)")
        self.label_created.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_created.setObjectName("label_created")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        with open('newdata.json','r') as file:
            data = json.load(file)
        with open('newdata.json','w') as file:
            for x in data:
                for i in x.keys():
                    if x[i][2] == x[i][4]:
                        x[i][5] = "Expire"
                        print("done")
                #if data[x][str(data.keys())][2] >= data[x][str(data.keys())][4]:# 2 == date of use __ 4 == date of expire)
                    #data[x][str(inputcard)][5] = "Expire"
            json.dump(data,file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "<strong>TATS</strong> for communication"))
        self.label_disc.setText(_translate("MainWindow", "<html><head/><body><p>We are <span style=\" font-weight:600; font-style:italic;\">everyWhere</span></p></body></html>"))
        self.label_loading.setText(_translate("MainWindow", "<html><head/><body><p>Updating...</p></body></html>"))
        self.label_created.setText(_translate("MainWindow", "<html><head/><body><p>Created by <span style=\" font-weight:600; font-style:italic;\">Tats</span> Team</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
